language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - 7.2

services:
  - mongodb

matrix:
  fast_finish: true

before_install:
  - travis_retry composer validate
  - pecl install -f mongodb

install:
  - travis_retry composer install

script:
  - vendor/bin/phpunit
