language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4

services:
  - mongodb

matrix:
  fast_finish: true

before_install:
  - travis_retry composer validate
  - echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini || return 0

install:
  - make dependencies

script:
  - make test
  - make qa
  - make license
  - make changelog
